import { env } from '../env.ts'
import { Logger } from '../Logger.ts'

export const CUSTOM_LINKS = env.GITLAB_COMMENT_CUSTOM_LINKS?.trim()

export const ADD_CHANGESET_URL_PLACEHOLDER_REGEXP =
  /\{\{\s*addChangesetUrl\s*\}\}/u

export const RANDOM_BOT_NAME_PATTERN =
  /^((?:project|group)_\d+_bot\w*)_[\da-z]+$/iu

export const GENERATED_BY_BOT_NOTE = 'Generated By Changesets GitLab Bot'

export const VERBOSE_LOGGER = new Logger('comment')
