import type { DiscussionNoteSchema, NoteSchema } from '@gitbeaker/core'
import { GENERATED_BY_BOT_NOTE, RANDOM_BOT_NAME_PATTERN } from './constants.ts'

export const isChangesetBotNote = (
  note: DiscussionNoteSchema | NoteSchema,
  username: string,
  random?: boolean
) =>
  (note.author.username === username
    || (random // We need to ensure the note is generated by us, // but we don't have an app bot like GitHub // @see https://github.com/apps/changeset-bot
      && RANDOM_BOT_NAME_PATTERN.exec(note.author.username)?.[1] === username))
  && note.body.includes(GENERATED_BY_BOT_NOTE)
